version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30

    working_directory: ~/code

    steps:
      - checkout

      - run:
          name: Setup JDK
          command: echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> $BASH_ENV

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Install Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug

      - run:
          name: Run Unit Tests
          command: ./gradlew testDebug

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
